spring:
  profiles:
    active: dev
  application:
    name: service-registration
  cloud:
    config:
      uri: http://localhost:8888/
      label: develop
  config:
    import: optional:configserver:http://localhost:8888/

